/**
 * Writes `dist/client/_headers` after the client build.
 *
 * ## Why this is generated rather than committed
 *
 * The SPA is served by Cloudflare Pages, not by the Worker: `public/_routes.json` scopes Functions
 * to `/api/*`, so a request for index.html never reaches Hono and no middleware can attach a header
 * to it. `_headers` is the only mechanism that applies to those responses.
 *
 * That rules out a nonce, which needs the document to be generated per request. So the one inline
 * script in index.html — the anti-flash theme applier, which has to run before first paint — has to
 * be allowed by hash. A hash committed by hand would be a hash that goes stale the first time
 * somebody edits a comment inside that script, and the failure mode is the worst kind: the build
 * succeeds, the tests pass, and the deployed page silently loses its theme script (or, with a
 * stricter policy, fails to boot). Computing it from the built file every time removes the
 * possibility.
 *
 * ## The policy, and the two concessions in it
 *
 * `style-src` allows `'unsafe-inline'` because this application positions the selection overlay,
 * the poster preview and every gallery card with React `style={{…}}` attributes, which CSP counts
 * as inline styles. Removing it would mean moving hundreds of computed positions into stylesheets
 * that cannot express them. Style injection is a real but much smaller hazard than script
 * injection, and the rest of the policy is written to be strict where it matters.
 *
 * `img-src` allows `blob:` because Excel and PNG export build a Blob and hand it to the browser
 * through `URL.createObjectURL`, and `connect-src` is `'self'` only — this application talks to
 * nothing but its own origin, which is the property worth pinning: an exfiltration path is the
 * first thing a script injection would want, and there is no host it could reach.
 */

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const clientDir = join(import.meta.dirname, '..', 'dist', 'client')
const html = readFileSync(join(clientDir, 'index.html'), 'utf8')

/**
 * Hash every inline `<script>` in the document.
 *
 * Scripts with a `src` are external and covered by `'self'`; only element content is hashed. The
 * bytes hashed are exactly the element's text content, which is what the browser hashes too — no
 * trimming, because whitespace is part of it.
 */
const inlineScripts = [...html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi)].map(
  (match) => match[1] ?? '',
)

const scriptHashes = inlineScripts.map(
  (source) => `'sha256-${createHash('sha256').update(source, 'utf8').digest('base64')}'`,
)

if (scriptHashes.length === 0) {
  // Not an error, but worth saying out loud: if the theme script is ever removed, the policy below
  // becomes stricter for free and nobody should have to wonder whether the hash step silently
  // stopped working.
  console.log("generate-headers: no inline scripts found; script-src will be 'self' alone")
}

const csp = [
  "default-src 'self'",
  `script-src 'self' ${scriptHashes.join(' ')}`.trim(),
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self'",
  // Same-origin only. This application has no third-party endpoint, so anything else is exfiltration.
  "connect-src 'self'",
  "worker-src 'self'",
  "manifest-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ')

/**
 * `X-Robots-Tag` alongside robots.txt, because they answer different questions.
 *
 * robots.txt asks a crawler not to fetch. `X-Robots-Tag: noindex` tells one that fetched anyway —
 * or that found the URL somewhere else entirely — not to index what it got. A research group's
 * unpublished measurements should be in neither a crawl nor an index, and the two mechanisms fail
 * independently.
 */
const headers = `# Generated by scripts/generate-headers.mjs — do not edit by hand.
# The script-src hash covers the inline theme applier in index.html and is recomputed on every
# build, so editing that script cannot leave a stale policy behind.
#
# Access-Control-Allow-Origin is set because Cloudflare Pages adds \`*\` to static assets by
# default, which Workers Static Assets did not. Nothing here is meant to be readable
# cross-origin: the client fetches its own assets same-origin, and \`/api/*\` is answered by the
# Function, whose response headers are the Worker's and are unaffected by this file. Overriding
# it to \`null\` is how the header is neutralised — Pages has no syntax for removing one, and
# \`null\` matches no origin.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: no-referrer
  Cross-Origin-Opener-Policy: same-origin
  Permissions-Policy: geolocation=(), camera=(), microphone=(), payment=(), usb=(), interest-cohort=()
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Robots-Tag: noindex, nofollow, noarchive
  Access-Control-Allow-Origin: null
`

writeFileSync(join(clientDir, '_headers'), headers)
console.log(`generate-headers: wrote _headers (${scriptHashes.length} inline script hash(es))`)
