"""Determinism: identical input, identical bytes — inside one pinned environment.

Two different guarantees are at work and the difference matters:

  * **Byte-identical** output is required for repeated renders of the same spec *in the same
    image*. That is what this file asserts. It is what makes a poster's `objectSha256` (see
    `packages/plot-spec/src/poster-record.ts`) a meaningful provenance record and what makes a
    retry of the idempotent poster endpoint a genuine no-op rather than a second, subtly
    different figure.
  * **Pixel-stable-not-byte-identical** is all that can be expected *across* operating systems,
    CPU architectures and library builds. FreeType hinting, zlib's compression level defaults and
    libpng filter choices all vary between builds. `test_reference_image.py` is the test that
    holds across those, using a tolerance; this file's byte equality is only ever asserted within
    a single process.
"""

from __future__ import annotations

import hashlib

import pytest

from poster_renderer.render import PNG_METADATA, render_png
from poster_renderer.validation import validate_spec
from poster_renderer.version import RENDERER_VERSION

from conftest import build_spec


def test_repeated_renders_are_byte_identical(validated_spec):
    first = render_png(validated_spec)
    second = render_png(validated_spec)
    assert hashlib.sha256(first).hexdigest() == hashlib.sha256(second).hexdigest()
    assert first == second


def test_rebuilt_spec_renders_identically(spec_dict):
    """The bytes depend on the spec's content, not on the object that carried it."""
    first = render_png(validate_spec(spec_dict))
    second = render_png(validate_spec(build_spec()))
    assert first == second


def test_png_carries_no_timestamp(validated_spec):
    """No `Creation Time`, no `tIME` chunk: two renders a day apart must still match."""
    png = render_png(validated_spec)
    assert PNG_METADATA == {"Software": f"AAT poster-renderer {RENDERER_VERSION} (aat-poster-v1)"}
    assert b"Creation Time" not in png
    assert b"tIME" not in png
    # The Software chunk is ours, not Matplotlib's autogenerated one, so a Matplotlib upgrade
    # cannot change the bytes without also changing a pixel.
    assert b"Matplotlib version" not in png
    assert RENDERER_VERSION.encode("ascii") in png


@pytest.mark.parametrize("field, value", [("title", "Drop 42"), ("dpi", 150), ("xMax", 1.2)])
def test_changing_any_field_changes_the_bytes(validated_spec, field, value):
    """Determinism must not be indifference: a different spec is a different poster."""
    baseline = render_png(validated_spec)
    changed = render_png(validate_spec(build_spec(**{field: value})))
    assert changed != baseline
