/// <reference path="../worker-configuration.d.ts" />

/**
 * The Worker entry point.
 *
 * Routing, in one place:
 *
 *   /api/auth/*   Better Auth (its own router: sessions, sign-out, and the AAT passkey plugin)
 *   /api/v1/*     the versioned application API
 *   everything else  never reaches here — `run_worker_first: ["/api/*"]` in wrangler.jsonc means
 *                    the static asset store answers the SPA without a Worker invocation at all.
 *
 * The API is versioned so that a future CLI or Python client can be added without the browser and
 * that client having to move in lockstep.
 *
 * Nothing here does analysis. The browser owns the numerical pipeline (see
 * docs/web-architecture.md); this Worker owns identity, authorization, quotas, metadata and the
 * poster renderer's leash.
 */

import { ApiError } from '@aat/shared'
import { Hono } from 'hono'
import { getAuth } from './auth/auth.ts'
import { ConfigurationError } from './config.ts'
import type { AppEnv } from './middleware/authorize.ts'
import { errorHandler, notFoundHandler } from './middleware/errors.ts'
import { adminRoutes } from './routes/admin.ts'
import { meRoutes } from './routes/me.ts'
import { posterRoutes } from './routes/posters.ts'
import { revisionRoutes } from './routes/revisions.ts'
import { runRoutes, workspaceRoutes } from './routes/runs.ts'

export { PosterRendererContainer } from './container/poster-renderer.ts'

const app = new Hono<AppEnv>()

app.onError(errorHandler)
app.notFound(notFoundHandler)

/**
 * Security headers for everything this Worker answers.
 *
 * `public/_headers` covers the SPA and its assets, and it covers ONLY those: `wrangler.jsonc` sets
 * `run_worker_first: ["/api/*"]`, so asset requests never reach Hono and — the half that matters
 * here — API responses are generated by Worker code and never pass through the static-asset layer
 * that applies `_headers`. Two mechanisms, because there are two response paths, and a header
 * missing from either one is missing.
 *
 * The policy is deliberately not the same as the SPA's. Nothing this Worker returns is a document:
 * it is JSON, or it is bytes from R2. So `default-src 'none'` is exactly right — there is no script
 * to run, no style to apply and no image to load in an API response, and `sandbox` makes that
 * explicit for anything a browser might nonetheless be persuaded to treat as a document.
 *
 * `X-Robots-Tag` is here as well as in `_headers` because a poster PNG is a perfectly indexable
 * object served on its own URL, and a search engine that reached one should not keep it.
 *
 * Set after `next()` and only on headers that are not already present, so a route that has decided
 * something more specific for itself — `streamObject`'s `Cache-Control: private, no-store`, its
 * own `Content-Type` — keeps its answer.
 */
app.use('*', async (context, next) => {
  await next()
  const headers = context.res.headers
  const defaults: Record<string, string> = {
    'content-security-policy': "default-src 'none'; frame-ancestors 'none'; base-uri 'none'; sandbox",
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'DENY',
    'referrer-policy': 'no-referrer',
    'cross-origin-resource-policy': 'same-origin',
    'x-robots-tag': 'noindex, nofollow, noarchive',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
  }
  for (const [name, value] of Object.entries(defaults)) {
    if (!headers.has(name)) headers.set(name, value)
  }
})

/**
 * Endpoints Better Auth serves that AAT deliberately does not offer.
 *
 * The catch-all below is still the right mount — enumerating routes would make an endpoint the
 * framework adds in an update silently 404, and passkey ceremonies would break on an upgrade. But
 * the same property cuts both ways: it publishes endpoints nobody here chose, and two of them were
 * reachable and wrong.
 *
 *  - `update-user` takes `z.record(z.string(), z.any())`, so any signed-in user could set their own
 *    `name` to anything of any length. The display name is not decoration in this system: it is the
 *    only human identity AAT holds (the address on the user record is synthetic — see
 *    auth/identity.ts), it is shown beside every run in the team gallery and throughout the admin
 *    console, and audit details are sanitised for bidi and zero-width characters precisely so that
 *    one member cannot render as another. A self-service rename with none of those bounds undoes
 *    that, and no capability in middleware/authorize.ts's table grants it — display names are set
 *    by an administrator when the invitation is issued.
 *  - `admin/*` is the Admin plugin's own surface: `impersonate-user`, `create-user`,
 *    `set-user-password`, `remove-user`, `list-users`. AAT's administration is `/api/v1/admin`,
 *    which is capability-checked, audited and quota-aware. Today these refuse only by accident —
 *    the plugin matches its default `admin`/`user` role names against AAT's `Admin`, misses, and
 *    denies. Renaming a role or configuring the plugin's `roles` would quietly open all of them,
 *    and `impersonate-user` in particular would name the *victim* as the actor in every subsequent
 *    audit row, destroying the attribution that makes the shared-workspace grant acceptable at all.
 *
 * `change-email` and `delete-user` are refused for the same reason: the address is synthetic and
 * account deletion has to release R2 objects and quota, which only `/api/v1/admin` does.
 */
const AUTH_PATHS_NOT_OFFERED = ['/api/auth/update-user', '/api/auth/change-email', '/api/auth/delete-user']

/**
 * Better Auth owns its prefix — session cookies, sign-out, and every endpoint the passkey plugin
 * adds — except for the paths above.
 */
app.all('/api/auth/*', async (context) => {
  const path = new URL(context.req.url).pathname
  if (AUTH_PATHS_NOT_OFFERED.includes(path) || path.startsWith('/api/auth/admin/')) {
    // NOT_FOUND rather than FORBIDDEN: these endpoints are not part of this API, and answering
    // "you may not" would describe a surface that is deliberately not on offer to anyone.
    throw new ApiError('RESOURCE_NOT_FOUND')
  }
  return getAuth(context.env).handler(context.req.raw)
})

const v1 = new Hono<AppEnv>()

v1.route('/me', meRoutes)
v1.route('/runs', runRoutes)
// There is no /projects. Runs are grouped by their tags — see worker/routes/runs.ts and
// migration 0003 for why the projects entity was removed rather than finished.
// The team gallery. Separate from /runs because it requires a capability /runs does not
// (`workspace:read`), and this router mounts capabilities as middleware so the route table stays
// the place where authorization can be read.
v1.route('/workspace', workspaceRoutes)
// Revision, snapshot and source-backup routes carry their own full paths (/runs/... and
// /revisions/...) because a snapshot belongs to a revision but is reached through its run.
v1.route('/', revisionRoutes)
v1.route('/', posterRoutes)
v1.route('/admin', adminRoutes)

app.route('/api/v1', v1)

/**
 * A Worker that starts without its secrets is a Worker that will do the wrong thing quietly — most
 * dangerously, run a passkey ceremony under an RP ID it invented. Configuration errors are caught
 * at the edge and answered as INTERNAL, with the real reason logged for an operator; the
 * alternative, a default RP ID derived from the request's Host header, is how every user's
 * credential gets invalidated at once.
 */
export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    try {
      return await app.fetch(request, env, ctx)
    } catch (error) {
      if (error instanceof ConfigurationError) {
        console.error(JSON.stringify({ configurationError: error.message }))
        return Response.json({ error: new ApiError('INTERNAL').toPayload() }, { status: 500 })
      }
      throw error
    }
  },
} satisfies ExportedHandler<Env>
